apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: lab3v
type: Opaque
data:
  # Base64 encoding: "root" -> cm9vdA==
  # Base64 encoding: "12345" -> MTIzNDU=
  username: cm9vdA==
  password: MTIzNDU=
  # Base64 encoding: "lab3v" -> bGFiM3Y=
  database: bGFiM3Y=